# -*- coding: utf-8 -*-
"""Indian_flag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fgFeqmM_WUR2O4Uk5dJ9G26VlxiJybuZ
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle, Circle, Polygon

# Set up the figure and axis
fig, ax = plt.subplots()
ax.set_xlim(0, 12)
ax.set_ylim(0, 7)
ax.axis('off')

# Draw the flag rectangles
colors = ['#FF9933', 'white', 'green']
for i, color in enumerate(reversed(colors)):
    ax.add_patch(Rectangle((0, i*2 + 1), 12, 2, facecolor=color, edgecolor='grey'))

# Draw the Ashoka Chakra
center_x, center_y = 6, 4
radius = 0.8
ax.add_patch(Circle((center_x, center_y), radius, fill=False, color='#000088', linewidth=7))
plt.plot(center_x, center_y, marker='o', color='#000088', markersize=9.5)

# Draw the 24 spokes
for i in range(24):
    angle = np.pi * i / 12
    x = center_x + radius * np.cos(angle)
    y = center_y + radius * np.sin(angle)
    ax.plot([center_x, x], [center_y, y], color='#000088', linewidth=1)

# Final display and message
for _ in range(3):
    print("----------Happy Independence Day----------")

plt.axis('equal')
plt.show()